document.write("<ul>");
document.write("<li><a href='index.html'>Home</a></li>");
document.write("<li>");
document.write("<a href='#'>Dropdown</a>");
document.write("<ul>");
document.write("<li><a href='#'>Lorem ipsum dolor</a></li>");
document.write("<li><a href='#'>Magna phasellus</a></li>");
document.write("<li><a href='#'>Etiam dolore nisl</a></li>");
document.write("<li>");
document.write("<a href='#'>And a submenu &hellip;</a>");
document.write("<ul>");
document.write("<li><a href='#'>Lorem ipsum dolor</a></li>");
document.write("<li><a href='#'>Phasellus consequat</a></li>");
document.write("<li><a href='#'>Magna phasellus</a></li>");
document.write("<li><a href='#'>Etiam dolore nisl</a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li><a href='#'>Veroeros feugiat</a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li><a href='left-sidebar.html'>Left Sidebar</a></li>");
document.write("<li><a href='right-sidebar.html'>Right Sidebar</a></li>");
document.write("<li><a href='no-sidebar.html'>No Sidebar</a></li>");
document.write("</ul>");
