document.write("<ul>");
document.write("<li><a href='index.html'>Home</a></li>");
document.write("<li>");
document.write("<a href='#'>Science Products</a>");
document.write("<ul>");
document.write("<li><a href='publications.html'>Publications</a></li>");
document.write("<li><a href='reduced.html'>Reduced Data</a></li>");
document.write("<li><a href='models.html'>Lensing Models</a></li>");
//document.write("<li>");
//document.write("<a href='#'>And a submenu &hellip;</a>");
//document.write("<ul>");
//document.write("<li><a href='#'>Lorem ipsum dolor</a></li>");
//document.write("<li><a href='#'>Phasellus consequat</a></li>");
//document.write("<li><a href='#'>Magna phasellus</a></li>");
//document.write("<li><a href='#'>Etiam dolore nisl</a></li>");
//document.write("</ul>");
//document.write("</li>");
//document.write("<li><a href='#'>Veroeros feugiat</a></li>");
document.write("</ul>");
document.write("</li>");
//document.write("<li><a href='right-sidebar.html'>Right Sidebar</a></li>");
document.write("<li><a href='images.html'>Color Images!</a></li>");
document.write("<li><a href='socials.html'>Social Media</a></li>");
document.write("</ul>");
